name: First Workflow
on: workflow_dispatch # manual trigger
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "hello"
      - name: Print Goodbye
        run: echo "bye"
