name: First Workflow
on: workflow_dispatch # manual trigger
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@v4
      - name: Display Environment Details
        run: |
          ls -latr
          python --version
          python -m pip freeze
      - name: Print Goodbye
        run: echo "bye"
